######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 8 23:55:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
HEADERS += main.h
SOURCES += main.cpp \
    atack.cpp \
    thimble.cpp \
    gipsy.cpp \
    log.cpp \
    pet-trainer.cpp \
    arena.cpp

FORMS += \
    mainwindow.ui

RESOURCES += \
    resources.qrc
